/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as PomockaRouteImport } from './routes/pomocka'
import { Route as ObchodnePodmienkyRouteImport } from './routes/obchodne-podmienky'
import { Route as KurzRouteImport } from './routes/kurz'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FormularVyplnenyRouteImport } from './routes/formular-vyplneny'
import { Route as FormularRouteImport } from './routes/formular'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiFormEmailsRouteImport } from './routes/api/form-emails'
import { Route as ApiBriefEmailsRouteImport } from './routes/api/brief-emails'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminCrmLoginRouteImport } from './routes/admin.crm-login'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PomockaRoute = PomockaRouteImport.update({
  id: '/pomocka',
  path: '/pomocka',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodnePodmienkyRoute = ObchodnePodmienkyRouteImport.update({
  id: '/obchodne-podmienky',
  path: '/obchodne-podmienky',
  getParentRoute: () => rootRouteImport,
} as any)
const KurzRoute = KurzRouteImport.update({
  id: '/kurz',
  path: '/kurz',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularVyplnenyRoute = FormularVyplnenyRouteImport.update({
  id: '/formular-vyplneny',
  path: '/formular-vyplneny',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularRoute = FormularRouteImport.update({
  id: '/formular',
  path: '/formular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormEmailsRoute = ApiFormEmailsRouteImport.update({
  id: '/api/form-emails',
  path: '/api/form-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefEmailsRoute = ApiBriefEmailsRouteImport.update({
  id: '/api/brief-emails',
  path: '/api/brief-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmLoginRoute = AdminCrmLoginRouteImport.update({
  id: '/admin/crm-login',
  path: '/admin/crm-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/pomocka': typeof PomockaRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/crm-login': typeof AdminCrmLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/api/brief-emails': typeof ApiBriefEmailsRoute
  '/api/form-emails': typeof ApiFormEmailsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/pomocka': typeof PomockaRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/crm-login': typeof AdminCrmLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/api/brief-emails': typeof ApiBriefEmailsRoute
  '/api/form-emails': typeof ApiFormEmailsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/pomocka': typeof PomockaRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/crm-login': typeof AdminCrmLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/api/brief-emails': typeof ApiBriefEmailsRoute
  '/api/form-emails': typeof ApiFormEmailsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formular'
    | '/formular-vyplneny'
    | '/gdpr'
    | '/kurz'
    | '/obchodne-podmienky'
    | '/pomocka'
    | '/unsubscribe'
    | '/admin/crm'
    | '/admin/crm-login'
    | '/admin/reset-password'
    | '/api/brief-emails'
    | '/api/form-emails'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formular'
    | '/formular-vyplneny'
    | '/gdpr'
    | '/kurz'
    | '/obchodne-podmienky'
    | '/pomocka'
    | '/unsubscribe'
    | '/admin/crm'
    | '/admin/crm-login'
    | '/admin/reset-password'
    | '/api/brief-emails'
    | '/api/form-emails'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/formular'
    | '/formular-vyplneny'
    | '/gdpr'
    | '/kurz'
    | '/obchodne-podmienky'
    | '/pomocka'
    | '/unsubscribe'
    | '/admin/crm'
    | '/admin/crm-login'
    | '/admin/reset-password'
    | '/api/brief-emails'
    | '/api/form-emails'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormularRoute: typeof FormularRoute
  FormularVyplnenyRoute: typeof FormularVyplnenyRoute
  GdprRoute: typeof GdprRoute
  KurzRoute: typeof KurzRoute
  ObchodnePodmienkyRoute: typeof ObchodnePodmienkyRoute
  PomockaRoute: typeof PomockaRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminCrmLoginRoute: typeof AdminCrmLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  ApiBriefEmailsRoute: typeof ApiBriefEmailsRoute
  ApiFormEmailsRoute: typeof ApiFormEmailsRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomocka': {
      id: '/pomocka'
      path: '/pomocka'
      fullPath: '/pomocka'
      preLoaderRoute: typeof PomockaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodne-podmienky': {
      id: '/obchodne-podmienky'
      path: '/obchodne-podmienky'
      fullPath: '/obchodne-podmienky'
      preLoaderRoute: typeof ObchodnePodmienkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurz': {
      id: '/kurz'
      path: '/kurz'
      fullPath: '/kurz'
      preLoaderRoute: typeof KurzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formular-vyplneny': {
      id: '/formular-vyplneny'
      path: '/formular-vyplneny'
      fullPath: '/formular-vyplneny'
      preLoaderRoute: typeof FormularVyplnenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formular': {
      id: '/formular'
      path: '/formular'
      fullPath: '/formular'
      preLoaderRoute: typeof FormularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-emails': {
      id: '/api/form-emails'
      path: '/api/form-emails'
      fullPath: '/api/form-emails'
      preLoaderRoute: typeof ApiFormEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief-emails': {
      id: '/api/brief-emails'
      path: '/api/brief-emails'
      fullPath: '/api/brief-emails'
      preLoaderRoute: typeof ApiBriefEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm-login': {
      id: '/admin/crm-login'
      path: '/admin/crm-login'
      fullPath: '/admin/crm-login'
      preLoaderRoute: typeof AdminCrmLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormularRoute: FormularRoute,
  FormularVyplnenyRoute: FormularVyplnenyRoute,
  GdprRoute: GdprRoute,
  KurzRoute: KurzRoute,
  ObchodnePodmienkyRoute: ObchodnePodmienkyRoute,
  PomockaRoute: PomockaRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminCrmLoginRoute: AdminCrmLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  ApiBriefEmailsRoute: ApiBriefEmailsRoute,
  ApiFormEmailsRoute: ApiFormEmailsRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
