/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KurzRouteImport } from './routes/kurz'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FormularVyplnenyRouteImport } from './routes/formular-vyplneny'
import { Route as FormularRouteImport } from './routes/formular'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminCrmLoginRouteImport } from './routes/admin.crm-login'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const KurzRoute = KurzRouteImport.update({
  id: '/kurz',
  path: '/kurz',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularVyplnenyRoute = FormularVyplnenyRouteImport.update({
  id: '/formular-vyplneny',
  path: '/formular-vyplneny',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularRoute = FormularRouteImport.update({
  id: '/formular',
  path: '/formular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmLoginRoute = AdminCrmLoginRouteImport.update({
  id: '/admin/crm-login',
  path: '/admin/crm-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/crm-login': typeof AdminCrmLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/crm-login': typeof AdminCrmLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/crm-login': typeof AdminCrmLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formular'
    | '/formular-vyplneny'
    | '/gdpr'
    | '/kurz'
    | '/admin/crm'
    | '/admin/crm-login'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formular'
    | '/formular-vyplneny'
    | '/gdpr'
    | '/kurz'
    | '/admin/crm'
    | '/admin/crm-login'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/formular'
    | '/formular-vyplneny'
    | '/gdpr'
    | '/kurz'
    | '/admin/crm'
    | '/admin/crm-login'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormularRoute: typeof FormularRoute
  FormularVyplnenyRoute: typeof FormularVyplnenyRoute
  GdprRoute: typeof GdprRoute
  KurzRoute: typeof KurzRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminCrmLoginRoute: typeof AdminCrmLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kurz': {
      id: '/kurz'
      path: '/kurz'
      fullPath: '/kurz'
      preLoaderRoute: typeof KurzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formular-vyplneny': {
      id: '/formular-vyplneny'
      path: '/formular-vyplneny'
      fullPath: '/formular-vyplneny'
      preLoaderRoute: typeof FormularVyplnenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formular': {
      id: '/formular'
      path: '/formular'
      fullPath: '/formular'
      preLoaderRoute: typeof FormularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm-login': {
      id: '/admin/crm-login'
      path: '/admin/crm-login'
      fullPath: '/admin/crm-login'
      preLoaderRoute: typeof AdminCrmLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormularRoute: FormularRoute,
  FormularVyplnenyRoute: FormularVyplnenyRoute,
  GdprRoute: GdprRoute,
  KurzRoute: KurzRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminCrmLoginRoute: AdminCrmLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
