/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KurzRouteImport } from './routes/kurz'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FormularVyplnenyRouteImport } from './routes/formular-vyplneny'
import { Route as FormularRouteImport } from './routes/formular'
import { Route as IndexRouteImport } from './routes/index'

const KurzRoute = KurzRouteImport.update({
  id: '/kurz',
  path: '/kurz',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularVyplnenyRoute = FormularVyplnenyRouteImport.update({
  id: '/formular-vyplneny',
  path: '/formular-vyplneny',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularRoute = FormularRouteImport.update({
  id: '/formular',
  path: '/formular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formular': typeof FormularRoute
  '/formular-vyplneny': typeof FormularVyplnenyRoute
  '/gdpr': typeof GdprRoute
  '/kurz': typeof KurzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formular' | '/formular-vyplneny' | '/gdpr' | '/kurz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formular' | '/formular-vyplneny' | '/gdpr' | '/kurz'
  id: '__root__' | '/' | '/formular' | '/formular-vyplneny' | '/gdpr' | '/kurz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormularRoute: typeof FormularRoute
  FormularVyplnenyRoute: typeof FormularVyplnenyRoute
  GdprRoute: typeof GdprRoute
  KurzRoute: typeof KurzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kurz': {
      id: '/kurz'
      path: '/kurz'
      fullPath: '/kurz'
      preLoaderRoute: typeof KurzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formular-vyplneny': {
      id: '/formular-vyplneny'
      path: '/formular-vyplneny'
      fullPath: '/formular-vyplneny'
      preLoaderRoute: typeof FormularVyplnenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formular': {
      id: '/formular'
      path: '/formular'
      fullPath: '/formular'
      preLoaderRoute: typeof FormularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormularRoute: FormularRoute,
  FormularVyplnenyRoute: FormularVyplnenyRoute,
  GdprRoute: GdprRoute,
  KurzRoute: KurzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
